/**
 * GitHub Actions integration — generates and manages GitHub Actions workflows.
 *
 * @module github/actions
 */

/** CI job configuration */
export interface CIJob {
  /** Job name */
  name: string;
  /** Run command */
  run: string;
  /** Working directory */
  workingDirectory?: string;
  /** Environment variables */
  env?: Record<string, string>;
  /** Conditional execution */
  if?: string;
  /** Cache dependencies */
  cache?: boolean;
}

/** CI workflow configuration */
export interface CIWorkflow {
  /** Workflow name */
  name: string;
  /** Trigger events */
  on: string[];
  /** Node.js versions to test */
  nodeVersions?: string[];
  /** Jobs to run */
  jobs: CIJob[];
  /** Whether to use pnpm */
  usePnpm?: boolean;
}

/** Generated workflow YAML */
export interface GeneratedWorkflow {
  /** Workflow filename */
  filename: string;
  /** Workflow YAML content */
  content: string;
  /** Description */
  description: string;
}

/**
 * GitHub Actions manager.
 * Generates and manages GitHub Actions workflows.
 */
export class ActionsManager {
  /**
   * Generate a CI workflow
   */
  generateCI(config: CIWorkflow): GeneratedWorkflow {
    const lines: string[] = [];

    lines.push(`# ${config.name}`);
    lines.push(`# Auto-generated by codemind`);
    lines.push('');
    lines.push(`name: ${config.name}`);
    lines.push('');

    // Triggers
    lines.push('on:');
    for (const event of config.on) {
      lines.push(`  ${event}:`);
      if (event === 'pull_request') {
        lines.push('    branches: [main]');
      } else if (event === 'push') {
        lines.push('    branches: [main]');
      }
    }
    lines.push('');

    // Jobs
    lines.push('jobs:');
    lines.push('  ci:');
    lines.push('    runs-on: ubuntu-latest');
    lines.push('');

    // Strategy matrix
    if (config.nodeVersions && config.nodeVersions.length > 0) {
      lines.push('    strategy:');
      lines.push('      matrix:');
      lines.push(`        node-version: [${config.nodeVersions.join(', ')}]`);
      lines.push('');
    }

    // Steps
    lines.push('    steps:');
    lines.push('      - uses: actions/checkout@v4');
    lines.push('');

    // Setup pnpm
    if (config.usePnpm !== false) {
      lines.push('      - uses: pnpm/action-setup@v2');
      lines.push('        with:');
      lines.push('          version: latest');
      lines.push('');
    }

    // Setup Node.js
    lines.push('      - uses: actions/setup-node@v4');
    lines.push('        with:');
    lines.push("          node-version: ${{ matrix.node-version || '20' }}");
    if (config.usePnpm !== false) {
      lines.push("          cache: 'pnpm'");
    }
    lines.push('');

    // Install dependencies
    lines.push('      - name: Install dependencies');
    lines.push('        run: pnpm install --frozen-lockfile');
    lines.push('');

    // Run jobs
    for (const job of config.jobs) {
      lines.push(`      - name: ${job.name}`);
      if (job.workingDirectory) {
        lines.push(`        working-directory: ${job.workingDirectory}`);
      }
      if (job.if) {
        lines.push(`        if: ${job.if}`);
      }
      if (job.env && Object.keys(job.env).length > 0) {
        lines.push('        env:');
        for (const [key, value] of Object.entries(job.env)) {
          lines.push(`          ${key}: ${value}`);
        }
      }
      lines.push(`        run: ${job.run}`);
      lines.push('');
    }

    return {
      filename: 'ci.yml',
      content: lines.join('
'),
      description: config.name,
    };
  }

  /**
   * Generate a standard codemind CI workflow
   */
  generateStandardCI(): GeneratedWorkflow {
    return this.generateCI({
      name: 'Codemind CI',
      on: ['push', 'pull_request'],
      nodeVersions: ['18', '20', '22'],
      usePnpm: true,
      jobs: [
        { name: 'Lint', run: 'pnpm lint' },
        { name: 'Type check', run: 'pnpm typecheck' },
        { name: 'Test', run: 'pnpm test' },
        { name: 'Build', run: 'pnpm build' },
      ],
    });
  }

  /**
   * Generate a release workflow
   */
  generateRelease(): GeneratedWorkflow {
    const lines: string[] = [];
    lines.push('name: Release');
    lines.push('');
    lines.push('on:');
    lines.push('  push:');
    lines.push('    tags:');
    lines.push("      - 'v*'");
    lines.push('');
    lines.push('jobs:');
    lines.push('  release:');
    lines.push('    runs-on: ubuntu-latest');
    lines.push('    steps:');
    lines.push('      - uses: actions/checkout@v4');
    lines.push('      - uses: pnpm/action-setup@v2');
    lines.push('      - uses: actions/setup-node@v4');
    lines.push('        with: { node-version: "20", cache: "pnpm" }');
    lines.push('      - run: pnpm install --frozen-lockfile');
    lines.push('      - run: pnpm build');
    lines.push('      - run: pnpm test');
    lines.push('');

    return {
      filename: 'release.yml',
      content: lines.join('
'),
      description: 'Release workflow triggered by version tags',
    };
  }

  /**
   * Generate a codemind review workflow for PRs
   */
  generateCodemindReview(): GeneratedWorkflow {
    const lines: string[] = [];
    lines.push('name: Codemind Review');
    lines.push('');
    lines.push('on:');
    lines.push('  pull_request:');
    lines.push('    types: [opened, synchronize, reopened]');
    lines.push('');
    lines.push('jobs:');
    lines.push('  review:');
    lines.push('    runs-on: ubuntu-latest');
    lines.push('    permissions:');
    lines.push('      contents: read');
    lines.push('      pull-requests: write');
    lines.push('    steps:');
    lines.push('      - uses: actions/checkout@v4');
    lines.push('        with: { fetch-depth: 0 }');
    lines.push('      - uses: pnpm/action-setup@v2');
    lines.push('      - uses: actions/setup-node@v4');
    lines.push('        with: { node-version: "20", cache: "pnpm" }');
    lines.push('      - run: pnpm install --frozen-lockfile');
    lines.push('      - name: Run Codemind Review');
    lines.push('        run: pnpm cli review --format markdown --output review.md');
    lines.push('        env:');
    lines.push('          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}');
    lines.push('');

    return {
      filename: 'codemind-review.yml',
      content: lines.join('
'),
      description: 'Automated code review on PRs using Codemind',
    };
  }
}
